version: '2'
services:
  bootnode:
    build: ethereum-bootnode
    environment:
      - SVC_URI=http://ether-swarm-services:8090
      - BOOTNODE_PORT=30303
    links:
      - ether-swarm-services

  geth:
    build: ethereum
    ports:
      - "8080"
      - "8545"
      - "8546"
    environment:
      - ETHERBASE=0x68f75ae6de5921d0a5edb093e954a25406d0f6f4
      - SVC_URI=http://ether-swarm-services:8090
      - SVC_CACHE_URI=http://ether-swarm-cache:8091
    links:
      - bootnode
      - eth-netstats
      - ether-swarm-services

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=ether-swarm-services
      - POSTGRES_USER=ether-swarm-services
      - POSTGRES_DB=ether-swarm-services

  ether-swarm-services:
    build: ether-swarm-services
    environment:
      - GG_BALANCE=1000000000000000000
      - DB_DSN=host=postgres user=ether-swarm-services dbname=ether-swarm-services sslmode=disable password=ether-swarm-services
    ports:
      - "0.0.0.0:8090:8090"
    links:
      - postgres

  ether-swarm-cache:
    build: ether-swarm-cache
    ports:
      - "8091"

  browser-solidity:
    build: browser-solidity
    ports:
      - "8080"

  eth-netstats:
    build: eth-netstats
    environment:
      - WS_SECRET=toto
    ports:
      - "41235:3000"

  rev-proxy:
    build: nginx
    ports:
      - "41234:80"
    links:
      - geth
      - browser-solidity
