version: '2'
services:
  bootnode:
    build: ethereum-bootnode
    volumes:
      - ethvol:/ethvol

  geth:
    build: ethereum
    ports:
      - "8080"
      - "8545"
      - "8546"
    volumes:
      - ethvol:/ethvol
    environment:
      - DATA_DIR=/datadir
      - ACCOUNT_PASSWORD=deadbeef
      - GG_PATH_PKEYS=/ethvol/keys
      - GG_PATH_GENESIS=/ethvol/genesis.json
      - ENODE_HOST=bootnode
    links:
      - bootnode

  utils:
    build: utils
    environment:
      - GG_PATH_PKEYS=/ethvol/keys
      - GG_PATH_GENESIS=/ethvol/genesis.json
      - GG_ALLOCATOR=10
    volumes:
      - ethvol:/ethvol

volumes:
  ethvol: {}
