version: '2'
services:
  geth:
    build: ethereum
    ports:
      - "8080"
      - "8545"
      - "30303"
    volumes:
      - ethvol:/root/eth
    environment:
      - DATA_DIR=/root/eth/datadir
      - ENV_FILE=/root/eth/ENV.sh
      - ACCOUNT_PASSWORD=deadbeef
      - GG_PATH_PKEYS=/root/eth/keys
      - GG_PATH_GENESIS=/root/eth/genesis.json

volumes:
  ethvol: {}
