version: '2'
services:
  bootnode:
    build: ethereum-bootnode
    volumes:
      - ethvol:/ethvol

  geth:
    build: ethereum
    ports:
      - "8080"
      - "8545"
      - "8546"
    volumes:
      - ethvol:/ethvol
    environment:
      - DATA_DIR=/datadir
      - ACCOUNT_PASSWORD=deadbeef
      - GG_PATH_PKEYS=/ethvol/keys
      - GG_PATH_GENESIS=/ethvol/genesis.json
      - ENODE_HOST=bootnode
      - MINE=1 # Set to 0 to disable mining
    links:
      - bootnode
      - eth-netstats

  utils:
    build: utils
    environment:
      - GG_PATH_PKEYS=/ethvol/keys
      - GG_PATH_GENESIS=/ethvol/genesis.json
      - GG_ALLOCATOR=10
    volumes:
      - ethvol:/ethvol

  browser-solidity:
    build: browser-solidity
    ports:
      - "8080"

  eth-netstats:
    build: eth-netstats
    environment:
      - WS_SECRET=toto
    ports:
      - "41235:3000"

  rev-proxy:
    build: nginx
    ports:
      - "41234:80"
    links:
      - geth
      - browser-solidity

volumes:
  ethvol: {}
