version: '2'
services:
  bootnode:
    build: ethereum-bootnode
    environment:
      - SVC_URI=http://ether-swarm-services:8090
      - BOOTNODE_PORT=30303
    links:
      - ether-swarm-services

  geth:
    build: ethereum
    ports:
      - "8080"
      - "8545"
      - "8546"
    environment:
      - MINE=1 # Set to 0 to disable mining
      - SVC_URI=http://ether-swarm-services:8090
    links:
      - bootnode
      - eth-netstats
      - ether-swarm-services

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=ether-swarm-services
      - POSTGRES_USER=ether-swarm-services
      - POSTGRES_DB=ether-swarm-services

  ether-swarm-services:
    build: ether-swarm-services
    environment:
      - GG_EXTRA_DATA=Test42
      - GG_BALANCE=1000000000000000000
      - GG_COINBASE=0x6120de0b6b3a7640000
      - DB_DSN=host=postgres user=ether-swarm-services dbname=ether-swarm-services sslmode=disable password=ether-swarm-services
    ports:
      - "0.0.0.0:8090:8090"
    links:
      - postgres

  browser-solidity:
    build: browser-solidity
    ports:
      - "8080"

  eth-netstats:
    build: eth-netstats
    environment:
      - WS_SECRET=toto
    ports:
      - "41235:3000"

  rev-proxy:
    build: nginx
    ports:
      - "41234:80"
    links:
      - geth
      - browser-solidity
